name: huh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'huehueh'
          password: 'anon@#@#hehe69'
      - name: Build Docker image
        run: docker pull benbusby/whoogle-search
      - name: Run Docker container
        run: docker run --publish 5000:5000 --detach --name whoogle-search benbusby/whoogle-search:latest
      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 5000 --subdomain phoneinfoga
